<a href="https://colab.research.google.com/github/Arjun9271/Pytorch/blob/main/1_Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU not available.using cpu")

GPU is available
using GPU:Tesla T4


# Creating a Tensor

In [ ]:
# empty - will create a tensor

torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a = torch.empty(3,3)
a

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22]])

In [ ]:
# check type

type(a)

torch.Tensor

In [ ]:
print(type(a))

<class 'torch.Tensor'>


In [ ]:
#using zeros

torch.zeros(5,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# using ones

torch.ones(5,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# using function rand
# creates values between 0 and 1

torch.rand(2,3)

tensor([[0.6272, 0.6241, 0.2523],
        [0.6257, 0.8065, 0.2276]])

In [ ]:
torch.rand(2,3) # different values got

tensor([[0.1567, 0.8304, 0.5295],
        [0.7105, 0.3298, 0.6237]])

In [ ]:
# use of seed #manual_seed

torch.manual_seed(10)
torch.rand(5,4)



tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440],
        [0.7041, 0.5573, 0.6959, 0.9849],
        [0.2924, 0.4823, 0.6150, 0.4967]])

In [ ]:
torch.manual_seed(10)
torch.rand(5,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440],
        [0.7041, 0.5573, 0.6959, 0.9849],
        [0.2924, 0.4823, 0.6150, 0.4967]])

In [ ]:
# using tensor --------> custom tensors

torch.tensor([[2,0,2,5],[2,0,2,4]])

tensor([[2, 0, 2, 5],
        [2, 0, 2, 4]])

In [ ]:
# other ways to create the tensors

# arange
print(f"using arange ------> \n{torch.arange(0,20,2)}\n")  # its like range

# linspace
print(f"using linspace------>\n{torch.linspace(0,7,6)}\n") #produced 6 values equally between 0 and 7

# eye
print(f"using eye----------->\n{torch.eye(4)}\n")  #identity matrix


# full
print(f"using full----------->\n{torch.full((3,4),4)}")  #shape with a particular item






using arange ------> 
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

using linspace------>
tensor([0.0000, 1.4000, 2.8000, 4.2000, 5.6000, 7.0000])

using eye----------->
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

using full----------->
tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])


# Tensor Shapes

In [ ]:
x = torch.full((2,3),6)
x

tensor([[6, 6, 6],
        [6, 6, 6]])

In [ ]:
y = torch.tensor([[1,4,9],[16,25,36],[49,64,81]])
y

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
y.shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(y)

tensor([[139514194210192, 100564298509136, 100564298278432],
        [100564298267616,               0, 100564271310752],
        [100564274118048, 139513161746608,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(y)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# Tensor Data Types

In [ ]:
# finding data type

y.dtype

torch.int64

In [ ]:
# assign data type while creating a tensor

torch.tensor([[1,7,2,9],[1,7,1,0],[1,0,0,1]],dtype = torch.float32)

tensor([[1., 7., 2., 9.],
        [1., 7., 1., 0.],
        [1., 0., 0., 1.]])

In [ ]:
torch.tensor([1.0,8.0,27.0,64.0],dtype = torch.int32)

tensor([ 1,  8, 27, 64], dtype=torch.int32)

In [ ]:
x

tensor([[6, 6, 6],
        [6, 6, 6]])

In [ ]:
#using to() ---> to use to convert the existing one to other

x.to(torch.float32)

tensor([[6., 6., 6.],
        [6., 6., 6.]])

In [ ]:
# handled the error that arised before

torch.rand_like(y,dtype = torch.float32)

tensor([[0.4521, 0.0575, 0.0687],
        [0.0501, 0.0108, 0.0343],
        [0.1212, 0.0490, 0.0310]])

# Mathematical Operations

## 1. Scalar Operation

In [ ]:
x = torch.full((3,3),1)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
def operation(tens,option):
       if option == 'add':
            print(f"addition{'->'*50}\n{tens}\n")
       elif option == 'sub':
            print(f"subtraction{'->'*50}\n{tens}\n")
       elif option == 'mul':
            print(f"multiplication{'->'*50}\n{tens}\n")
       elif option == 'div':
            print(f"division{'->'*50}\n{tens}\n")
       elif option == 'pow':
            print(f"power{'->'*50}\n{tens}\n")
       elif option == "mod":
            print(f"modulus{'->'*50}\n{tens}\n")
       else:
            print("invalid operation")

In [ ]:
# addition

operation(x+2,'add')

#substraction -
operation(x-2,'sub')

# multiplication
operation(x*2,'mul')

#division
operation(x/3,'div')

#int division
operation(x//2,'div')

#power
k = x*5
operation(k**2,'pow')

# modulus

operation(k%3,'mod')


addition->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

subtraction->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
tensor([[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]])

multiplication->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

division->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

division->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

power->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->

# 2.Element Wise Operation

In [ ]:
a = torch.tensor([[2,0,0,1]])
b = torch.tensor([3,2,3,4])

print(a,end = "\n\n")
print(b)


# add
print(f"addition{'-'*50}\n{a+b}\n")

# sub
print(f"subtraction{'-'*50}\n{a-b}\n")

# mul
print(f"multiplication{'-'*50}\n{a*b}\n")

#div
print(f"division{'-'*50}\n{a//b}\n")

# power

print(f"power{'-'*50}\n{a**b}\n")


tensor([[2, 0, 0, 1]])

tensor([3, 2, 3, 4])
addition--------------------------------------------------
tensor([[5, 2, 3, 5]])

subtraction--------------------------------------------------
tensor([[-1, -2, -3, -3]])

multiplication--------------------------------------------------
tensor([[6, 0, 0, 4]])

division--------------------------------------------------
tensor([[0, 0, 0, 0]])

power--------------------------------------------------
tensor([[8, 0, 0, 1]])



In [ ]:
# absolute

vector = torch.tensor([-1,2,3,-4])

torch.abs(vector)

tensor([1, 2, 3, 4])

In [ ]:
#negative

torch.neg(vector)

tensor([ 1, -2, -3,  4])

In [ ]:
#round

float_val_tensor = torch.tensor([1.3,2.8,5.1,6.5,7.8])

torch.round(float_val_tensor)

tensor([1., 3., 5., 6., 8.])

In [ ]:
# ceil

torch.ceil(float_val_tensor)

tensor([2., 3., 6., 7., 8.])

In [ ]:
# floor

torch.floor(float_val_tensor)

tensor([1., 2., 5., 6., 7.])

In [ ]:
# clamp

torch.clamp(float_val_tensor,min = 2,max = 5)

tensor([2.0000, 2.8000, 5.0000, 5.0000, 5.0000])

# 3. Reduction Operation

In [ ]:
# low - inclusive and high - exclusive
e = torch.randint(size = (5,5),low = 1,high = 5)
e

tensor([[3, 3, 2, 1, 1],
        [3, 2, 4, 3, 2],
        [2, 2, 4, 2, 3],
        [2, 1, 3, 3, 3],
        [2, 1, 2, 4, 2]])

In [ ]:
# sum

torch.sum(e)

tensor(60)

In [ ]:
# sum along rows

torch.sum(e,dim = 1)

tensor([10, 14, 13, 12, 11])

In [ ]:
# sum along columns

torch.sum(e,dim = 0)

tensor([12,  9, 15, 13, 11])

In [ ]:
# mean

torch.mean(e,dtype = torch.float32)

tensor(2.4000)

In [ ]:
# mean along col

torch.mean(e,dim = 0,dtype = torch.float32)

tensor([2.4000, 1.8000, 3.0000, 2.6000, 2.2000])

In [ ]:
# median

torch.median(e)

tensor(2)

In [ ]:
# max and min
print(f"max:{torch.max(e)}\nmin:{torch.min(e)}")

max:4
min:1


In [ ]:
# product

torch.prod(e)

tensor(429981696)

In [ ]:
# standard deviation
e = e.to(torch.float32)
torch.std(e)

tensor(0.9129)

In [ ]:
# variance

torch.var(e)

tensor(0.8333)

In [ ]:
# argmax

torch.argmax(e)

tensor(7)

In [ ]:
# argmin

torch.argmin(e)

tensor(3)

# 4. Matrix Operations

In [ ]:
tensor_1 = [1,2,3]
tensor_2 = [[5,4,3,2],[1,2,3,4],[5,6,7,8]]

In [ ]:
f = torch.tensor(tensor_1)
g = torch.tensor(tensor_2)

In [ ]:
print(f,g,sep = '\n\n')

tensor([1, 2, 3])

tensor([[5, 4, 3, 2],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# matrix multiplication

torch.matmul(f,g)

tensor([22, 26, 30, 34])

In [ ]:
vector1 = torch.randint(size = (5,),low = 1,high = 5)
vector2 = torch.randint(size = (5,),low = 0,high = 5)

In [ ]:
vector1,vector2

(tensor([1, 4, 3, 2, 2]), tensor([2, 4, 4, 4, 4]))

In [ ]:
# dot product

torch.dot(vector1,vector2)

tensor(46)

In [ ]:
g

tensor([[5, 4, 3, 2],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
# transpose

torch.transpose(g,0,1)


tensor([[5, 1, 5],
        [4, 2, 6],
        [3, 3, 7],
        [2, 4, 8]])

In [ ]:
# det

torch.det(g)

RuntimeError: linalg.det: A must be batches of square matrices, but they are 3 by 4 matrices

In [ ]:
new_det = torch.randint(size = (3,3),low = 0,high = 5)

In [ ]:
new_det

tensor([[4, 4, 3],
        [3, 1, 3],
        [2, 1, 1]])

In [ ]:
new_det = new_det.to(torch.float32)

In [ ]:
new_det

tensor([[4., 4., 3.],
        [3., 1., 3.],
        [2., 1., 1.]])

In [ ]:
torch.det(new_det)

tensor(7.)

In [ ]:
# inverse


# Comparision Operations

In [ ]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([5,4,3,2,1])

In [ ]:
# greater than

print(a>b)

# less than

print(a<b)

# greater than equal to

print(a>=b)

# less than equal to

print(a<=b)



# not equal to

print(a!=b)


tensor([False, False, False,  True,  True])
tensor([ True,  True, False, False, False])
tensor([False, False,  True,  True,  True])
tensor([ True,  True,  True, False, False])
tensor([ True,  True, False,  True,  True])


# 6.Special Functions

In [ ]:
k = torch.randint(size = (2,3),low = -5,high = 5,dtype = torch.float32)
k

tensor([[-1.,  4., -4.],
        [ 3.,  4.,  2.]])

In [ ]:
# log

torch.log(k)

tensor([[   nan, 1.3863,    nan],
        [1.0986, 1.3863, 0.6931]])

In [ ]:
# exp

torch.exp(k)

tensor([[3.6788e-01, 5.4598e+01, 1.8316e-02],
        [2.0086e+01, 5.4598e+01, 7.3891e+00]])

In [ ]:
# sqrt

torch.sqrt(k)

tensor([[   nan, 2.0000,    nan],
        [1.7321, 2.0000, 1.4142]])

In [ ]:
# sigmoid

torch.sigmoid(k)

tensor([[0.2689, 0.9820, 0.0180],
        [0.9526, 0.9820, 0.8808]])

In [ ]:
# softmax

torch.softmax(k,dim = 1)

tensor([[6.6906e-03, 9.9298e-01, 3.3311e-04],
        [2.4473e-01, 6.6524e-01, 9.0031e-02]])

In [ ]:
# rel

torch.relu(k)

tensor([[0., 4., 0.],
        [3., 4., 2.]])

# Inplace Operations

In [ ]:
# function along with underscore will be used

In [ ]:
m = torch.randint(size = (2,3),low = -5,high = 5,dtype = torch.float32)
n = torch.randint(size = (2,3),low = -5,high = 5,dtype = torch.float32)

print(m,end = '\n\n')
print(n)

tensor([[-1.,  4.,  1.],
        [-1., -1.,  1.]])

tensor([[ 1.,  0.,  1.],
        [-2.,  1., -5.]])


In [ ]:
m.add_(n)

tensor([[ 0.,  4.,  2.],
        [-3.,  0., -4.]])

In [ ]:
m

tensor([[ 0.,  4.,  2.],
        [-3.,  0., -4.]])

In [ ]:
n

tensor([[ 1.,  0.,  1.],
        [-2.,  1., -5.]])

In [ ]:
torch.relu(m)

tensor([[0., 4., 2.],
        [0., 0., 0.]])

In [ ]:
m

tensor([[ 0.,  4.,  2.],
        [-3.,  0., -4.]])

In [ ]:
m.relu_()

tensor([[0., 4., 2.],
        [0., 0., 0.]])

In [ ]:
m

tensor([[0., 4., 2.],
        [0., 0., 0.]])

# Copying a tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9811, 0.7662, 0.3325],
        [0.2877, 0.6533, 0.3310]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9811, 0.7662, 0.3325],
        [0.2877, 0.6533, 0.3310]])

In [ ]:
a.add_(1)

tensor([[1.9811, 1.7662, 1.3325],
        [1.2877, 1.6533, 1.3310]])

In [ ]:
b

tensor([[1.9811, 1.7662, 1.3325],
        [1.2877, 1.6533, 1.3310]])

In [ ]:
print(id(a))
print(id(b))

139513162024256
139513162024256


In [ ]:
b = a.clone()
b

tensor([[1.9811, 1.7662, 1.3325],
        [1.2877, 1.6533, 1.3310]])

In [ ]:
a[0][0] = 3

In [ ]:
a

tensor([[3.0000, 1.7662, 1.3325],
        [1.2877, 1.6533, 1.3310]])

In [ ]:
b

tensor([[1.9811, 1.7662, 1.3325],
        [1.2877, 1.6533, 1.3310]])

In [ ]:
print(id(a))
print(id(b))

139513162024256
139513162025696


# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device  = torch.device('cuda')

In [ ]:
# creating a new tensor on GPU

torch.rand((2,3),device = device)

tensor([[0.9835, 0.2422, 0.7872],
        [0.0981, 0.6317, 0.2422]], device='cuda:0')

In [ ]:
# moving an existing tensor to gpu

a = torch.rand((2,3))
a

tensor([[0.6552, 0.2441, 0.1906],
        [0.4875, 0.7936, 0.9259]])

In [ ]:
b = a.to(device)

In [ ]:
b+5

tensor([[5.6552, 5.2441, 5.1906],
        [5.4875, 5.7936, 5.9259]], device='cuda:0')

# Reshaping the tensors

In [ ]:
a = torch.eye(4)
a

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
# reshape

a.reshape(2,2,2,2)

tensor([[[[1., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 0.]]],


        [[[0., 0.],
          [1., 0.]],

         [[0., 0.],
          [0., 1.]]]])

In [ ]:
# flatten

a.flatten()

tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.6105, 0.2030, 0.7614, 0.6949],
         [0.7133, 0.3333, 0.4325, 0.7307],
         [0.7065, 0.8321, 0.2001, 0.8140]],

        [[0.3055, 0.4874, 0.2647, 0.3518],
         [0.8371, 0.9271, 0.6741, 0.1249],
         [0.3156, 0.8468, 0.3651, 0.0916]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze -----> adds new dimension
# useful during classification
# during prediction model accept as batches: n*266*266*3
#image size
c = torch.rand(266,226,3)
c.unsqueeze(dim = 0).shape

torch.Size([1, 266, 226, 3])

In [ ]:
c.unsqueeze(dim = 1).shape

torch.Size([266, 1, 226, 3])

In [ ]:
# squeeze

d = torch.rand(1,20)
d.squeeze(dim = 0).shape

torch.Size([20])

# Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,7,2,9])
a

tensor([1, 7, 2, 9])

In [ ]:
b = a.numpy()
b

array([1, 7, 2, 9])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,7,2,9])
c

array([1, 7, 2, 9])

In [ ]:
torch.from_numpy(c)

tensor([1, 7, 2, 9])

In [ ]:
import torch
import time

# Create random matrices on CPU
size = 10000  # Adjust the size as needed
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print(f"Speedup (CPU time / GPU time): {cpu_time / gpu_time:.4f}")

Time on CPU: 14.9630 seconds
Time on GPU: 0.5706 seconds
Speedup (CPU time / GPU time): 26.2224
