<a href="https://colab.research.google.com/github/Arjun9271/Pytorch/blob/main/4_Pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NN module

The torch.nn module in PyTorch is a core library that provides a wide array of classes and
functions designed to help developers build neural networks efficiently and effectively. It
abstracts the complexity of creating and training neural networks by offering pre-built layers,
loss functions, activation functions, and other utilities, enabling you to focus on designing and
experimenting with model architectures.
Key Components of torch.nn:
#### 1. Modules (Layers):
nn.Module:
- The base class for all neural network modules. Your custom models and
layers should subclass this class.

- Common Layers: Includes layers like nn.Linear (fully connected layer), nn.Conv2d
(convolutional layer), nn.LSTM (recurrent layer), and many others.

#### 2. Activation Functions:
- Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce non-linearities to the
model, allowing it to learn complex patterns.

#### 3. Loss Functions:
- Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to
quantify the difference between the model's predictions and the actual targets.

#### 4. Container Modules:
**nn.Sequential:**
-  A sequential container to stack layers in order.

#### 5. Regularization and Dropout:
- Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve
the model's ability to generalize to new data.

In [1]:
import torch

# device name
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [18]:
# create a model class

import torch
import torch.nn as nn

class Model(nn.Module):
      def __init__(self,num_features):

            super().__init__()
            self.linear1 = nn.Linear(num_features,3)
            self.relu = nn.ReLU()
            self.linear2 = nn.Linear(3,1)
            self.sigmoid = nn.Sigmoid()

      def forward(self,features):
            out = self.linear1(features)
            out = self.relu(out)
            out = self.linear2(out)
            out = self.sigmoid(out)

            return out

In [19]:
# create a dataset

features = torch.rand(10,5)

# create model
model = Model(features.shape[1])


# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5038],
        [0.4953],
        [0.5051],
        [0.5079],
        [0.4953],
        [0.5042],
        [0.5025],
        [0.5055],
        [0.4915],
        [0.5036]], grad_fn=<SigmoidBackward0>)

In [21]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-1.9160e-04,  3.3154e-01, -4.3443e-01,  3.0936e-01, -3.9135e-01],
        [ 2.5177e-01,  6.0479e-02, -3.2913e-01,  2.9339e-01, -1.4074e-01],
        [-1.1564e-01, -1.2946e-01,  3.1292e-01,  4.2859e-01,  2.4887e-01]],
       requires_grad=True)

In [22]:
# show bias

model.linear1.bias

Parameter containing:
tensor([ 0.3249, -0.1545, -0.0565], requires_grad=True)

In [23]:
! pip install torchinfo

In [24]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [29]:
# create a model class

import torch
import torch.nn as nn

class Model_v(nn.Module):
      def __init__(self,num_features):

            super().__init__()
            self.network = nn.Sequential(

            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),

            )

      def forward(self,features):

            out = self.network(features)

            return out

In [30]:
# create a dataset

features = torch.rand(10,5)

# create model
new_model = Model_v(features.shape[1])


# call model for forward pass
# model.forward(features)
new_model(features)

tensor([[0.3850],
        [0.4115],
        [0.3627],
        [0.3934],
        [0.3959],
        [0.3693],
        [0.3931],
        [0.4138],
        [0.4042],
        [0.3541]], grad_fn=<SigmoidBackward0>)

In [31]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [33]:
df.shape

(569, 33)

In [34]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [35]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [36]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# scaling

In [37]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
X_train

array([[-1.22833559, -0.31251905, -1.15607997, ..., -0.26809477,
        -0.44806211,  1.73269911],
       [-0.9025944 , -1.02476353, -0.87471114, ..., -0.14106638,
         0.61911579,  0.35776581],
       [ 1.50101486,  1.28198958,  1.4207522 , ...,  0.4502205 ,
        -0.94669983, -1.26021673],
       ...,
       [ 1.75180176,  0.46865233,  1.61677113, ...,  0.41846341,
        -1.03213619, -0.69941716],
       [ 0.86982087,  0.83626239,  0.73876967, ..., -0.52139542,
        -0.69971105, -1.0307003 ],
       [-0.6518075 , -1.02476353, -0.64030517, ..., -1.0459924 ,
         0.34416603, -0.44878956]])

In [39]:
y_train

176    B
342    B
451    M
233    M
96     B
      ..
107    B
332    B
237    M
261    M
349    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [40]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [41]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,

# Numpy arrays to PyTorch tensors

In [42]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [43]:
X_train_tensor.shape

torch.Size([455, 30])

In [44]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [51]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


# Important Parameters

In [61]:
learning_rate = 0.1
epochs = 200

In [62]:
# define loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [63]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7900774478912354
Epoch: 2, Loss: 0.5900514125823975
Epoch: 3, Loss: 0.48187899589538574
Epoch: 4, Loss: 0.4151653051376343
Epoch: 5, Loss: 0.36949047446250916
Epoch: 6, Loss: 0.3359454572200775
Epoch: 7, Loss: 0.31007635593414307
Epoch: 8, Loss: 0.2894035875797272
Epoch: 9, Loss: 0.27243098616600037
Epoch: 10, Loss: 0.25819817185401917
Epoch: 11, Loss: 0.24605782330036163
Epoch: 12, Loss: 0.23555651307106018
Epoch: 13, Loss: 0.2263661026954651
Epoch: 14, Loss: 0.21824276447296143
Epoch: 15, Loss: 0.21100112795829773
Epoch: 16, Loss: 0.20449768006801605
Epoch: 17, Loss: 0.19861923158168793
Epoch: 18, Loss: 0.19327540695667267
Epoch: 19, Loss: 0.18839280307292938
Epoch: 20, Loss: 0.18391139805316925
Epoch: 21, Loss: 0.17978142201900482
Epoch: 22, Loss: 0.17596116662025452
Epoch: 23, Loss: 0.1724155694246292
Epoch: 24, Loss: 0.16911470890045166
Epoch: 25, Loss: 0.16603298485279083
Epoch: 26, Loss: 0.16314831376075745
Epoch: 27, Loss: 0.1604415774345398
Epoch: 28, Loss: 0

# Evaluation

In [66]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.6).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5872576236724854
